### ISSUE TITLE
Current streak error when full year of contributions

### ISSUE THREAD

**Issue by Naramsim** [Naramsim/GithubOriginalStreak#22]
https://github.com/nelsonic
Here current streak start and end date are not written

**Comment by sarbbottam** [comment]
BTW, there is a limitation with this extension, `max-current-streak will never be more than 369, even if it is actually.

As the data is extracted from the markup, and markup displays data for only last 369 days.

**Comment by Naramsim** [comment]
Yes, we could add more years by querying Github API per user

**Comment by sarbbottam** [comment]
Is the original issue still reproducible?

**Comment by Naramsim** [comment]
It is impossible to get all the past events:

#### GitHub:

> Only events created within the past 90 days will be included in timelines. Events older than 90 days will not be included (even if the total number of events in the timeline is less than 300).

Here is the link to fetch the very last events Github give for my profile: https://api.github.com/users/Naramsim/events?page=3&per_page=200 We can get up to 300 events :anguished:

**Comment by Naramsim** [comment]
I have created this fiddle that gets those 300 events, we should embed it and store the count in LocalStorage. It is too complicated and should start working only after 1 year from now... 
https://jsfiddle.net/m18vkLdo/
