### ISSUE TITLE
change streak color

### ISSUE THREAD

**Issue by sarbbottam** [Naramsim/GithubOriginalStreak#26]
In stead of 
`localStorage.setItem("blueSky", 1)` 
let's do 
`localStorage.setItem("color-scheme", "blue-sky")`

Why?

Let's get fancier ...

multiple color-scheme, `blue-sky`, `golden-orange`, `pinky-purple` etc ...

---

And maybe later on from browser action? For example, user clicks on the extension icon, display a color scheme chooser. Whenever user updates the color-scheme, it is set to `local-storage/color-scheme`
- [x] Multiple color scheme
- [ ] Browser action to change color scheme

**Comment by sarbbottam** [comment]
@Naramsim thoughts?

**Comment by Naramsim** [comment]
It could be, for sure.

**Comment by Naramsim** [comment]
On the new PR I've added "halloween" mode

**Comment by sarbbottam** [comment]
Fixed as part of #28
