### ISSUE TITLE
inject.js & inject.css

### ISSUE THREAD

**Issue by sarbbottam** [Naramsim/GithubOriginalStreak#3]
[`/chrome/src/inject/inject.{js,css}` is shared at `/firefox/data`](https://github.com/Naramsim/GithubOriginalStreak/blob/master/gulpfile.js#L6-L10)

Does it make sense, to take out `inject.js` and `inject.css` from `chrome`, place it in `./src` and copy them to `firefox` and `chorme` only during building the respective extensions?

**Comment by Naramsim** [comment]
I am fine right now, I just run `gulp watch` and gulp syncs the two folders whenever I save.
I don't want to copy and paste every time.
Just keep in mind to start the gulp session and work on chrome files.

**Comment by Naramsim** [comment]
Fixed, thanks
