### ISSUE TITLE
Streak doesn't correctly look back farther than a few days past a year

### ISSUE THREAD

**Issue by albertyw** [Naramsim/GithubOriginalStreak#35]
I tried installing GithubOriginalStreak but I found that the chrome plugin does not correctly look back more than a few days past a year.  My streak says 371 days but it should go well beyond that.

**Comment by Naramsim** [comment]
Yes, I will deploy an update that (in the case of a full contribution calendar) will show a message to set a custom start date.
For now just, tell me when your streak started. I will update a gist(the one of #34). So your streak will show correctly to all the users that are using this extension.

**Comment by LeonTG** [comment]
I just installed this and saw that option but I accidentally clicked off it, how do I get it back?

**Comment by albertyw** [comment]
In a browser dev tools window on github.com, run `localStorage.removeItem('customStartStreakDateWasAsked')` and refresh your profile page.

I also did it myself originally by reverse engineering the code and updating the github gist holding the data directly.

**Comment by LeonTG** [comment]
@albertyw The first thing didn't work, nothing is popping up

**Comment by Naramsim** [comment]
Yeah, you could clear all our flags in the localstorage or just tell me the date when your streak started and I will update it 😄 

You can write me to my email. (On my profile)

**Comment by LeonTG** [comment]
@Naramsim It started September, 12th, 2015

**Comment by Naramsim** [comment]
Done: https://github.com/LeonTG

**Comment by LeonTG** [comment]
@Naramsim Thank you! :)
