### ISSUE TITLE
Premature Streak Reset

### ISSUE THREAD

**Issue by wbraswell** [Naramsim/GithubOriginalStreak#38]
![wbraswell_20160717-github_streak_bug](https://cloud.githubusercontent.com/assets/1772630/16905573/9def44a0-4c6d-11e6-9708-ed714aad596a.png)

The "Current Streak" should not be reset to "0 Days" until my local clock hits midnight.  If it is not possible to check my current time zone, then delay streak reset until the very last time zone on Earth hits midnight.

As it is now, my Current Streak is almost always showing "0 Days" which is obviously incorrect, and is not the way the original Github streak software operated.

You can see in the attached screenshot that it is only 10pm in my local time zone, but already I have 2 empty squares showing up and a "0 Days" as my streak.  I will also see "0 Days" as my Current Streak even if I check it in the morning instead of at night.  So again, the Current Streak is incorrectly getting reset to "0 Days" at least 24 hours too early, which is quite a lot.

**Comment by Naramsim** [comment]
The local streak does rely on local time zone. It is calculated by your computer.
As soon a day starts it is reset to 0 days because that day you haven't contributed. As soon you make a contribution it will show the correct streak.
In your screenshot I saw that you have two noncontributing days, isn´t that 0 day streak correct?

The streak is reset to 0 when days starts

**Comment by Naramsim** [comment]
![screenshot 159](https://cloud.githubusercontent.com/assets/8996268/16908681/cdfd50aa-4ccd-11e6-8230-abc90f2df27d.png)
This is your streak right now. Longest is correct since it looked to the backup data. The current is 0 because you haven't contributed today.

**Comment by wbraswell** [comment]
No, that is not the correct behavior.

The original Github streak does not reset me to 0 days until midnight of my local time zone.

**Comment by wbraswell** [comment]
And also the browser plugin must not be checking my local timezone correctly, because it shows an empty block for tomorrow many hours before midnight, which is also a different incorrect behavior.  

It is okay to show the block for tomorrow an hour or two before midnight in my local timezone, but not several hours in advance, and it definitely should have not have an effect on my streak.

Should I file this as a separate bug or keep it as part of this bug report?

**Comment by Naramsim** [comment]
It is okay here.
So when a new day starts I will not reset the current streak. I'll reset it only if you are not contributing for two consecutive days. Seems fine?

**Comment by Naramsim** [comment]
![days](http://i.imgur.com/ldDKlnr.png)
Here an image, proving that you are right , thanks

**Comment by wbraswell** [comment]
@Naramsim 
I am still experiencing this issue.  I have not pushed any commits yet for today (Jul 21), and my streak says "0 days".

**Comment by Naramsim** [comment]
Be patient @wbraswell, the new version is not out yet.

**Comment by wbraswell** [comment]
@Naramsim 
Oh I see, on Github and other ticketing systems, we do not "close" a bug report until the actual bug fix has been released, so naturally I assumed that since you have marked this issue as "closed" that you have released the bug fix.

**Comment by Naramsim** [comment]
Ok, I've pushed the repo with the code that fixes the bug. But I didn't submit it the stores

**Comment by wbraswell** [comment]
@Naramsim 
Thank you for explaining.

With my own programming projects, which require code to be installed by the user, I do mark the bug reports as "closed" when I push the fixes to Github, because it is expected that my users can and will install the latest code directly from Github.

However, for a browser plugin such as yours, which is installed & updated automatically based on the browser plugin stores, I believe you are correct in re-opening the bug report until the store has been updated, since most of your users (like me) will not know how to install a browser plugin directly from Github.

So yes, it is good to keep this Github issue as "open" until the browser plugin stores have been updated.

**Comment by wbraswell** [comment]
@Naramsim 
When I loaded up Github just now, I saw a new popup window for selecting a new start date, it looks good!
(I did not need to set a new start date, so I dismissed the popup dialog.)

**Comment by Naramsim** [comment]
Hey @wbraswell, thanks. It will never show again. Has the issue been resolved? I hope so. Thank you for pointing it out.

**Comment by wbraswell** [comment]
@Naramsim 
Okay both issues now appear to be resolved!
A blank square did not appear until my local clock hit midnight, and my streak did not get reset to 0 immediately, so everything is correct now.
Great job, keep up the good work, and thanks!
:+1:
