### ISSUE TITLE
Contributions in the last year displays wrong date range

### ISSUE THREAD

**Issue by TDA** [Naramsim/GithubOriginalStreak#42]
So, while the current streak and the longest streak show the right stats, the "Contributions in the last year" also shows the _same_ stats. This isn't how GitHub used to show it IIRC. More like last one year (~ +/- 365 days). I would like to include that I did use the date setter, so not sure if it occurs otherwise :)

Screen:
<img width="746" alt="screenshot 2016-08-25 20 39 01" src="https://cloud.githubusercontent.com/assets/432707/17993358/fa73d4d4-6b03-11e6-921d-3437d473b297.png">

It says "June 2, 2015 to Aug 25, 2016" while it should be something like "Aug 24, 2015 to Aug 25, 2016" :)

@Naramsim 

P.S: Also thank you for this wonderful tool :)

**Comment by Naramsim** [comment]
Hi @TDA, thanks for reporting.
Just fixed the error:
![screenshot 164](https://cloud.githubusercontent.com/assets/8996268/17998049/954d816c-6b72-11e6-92ef-268e44d5bae2.png)

I will upload the new version to the stores now.
If you are on firefox or on opera, you could receive the update in a week

**Comment by TDA** [comment]
@Naramsim Wow, that was insanely fast! thank you so much!! 👍
