### ISSUE TITLE
New Github design

### ISSUE THREAD

**Issue by Naramsim** [Naramsim/GithubOriginalStreak#46]
Github has just released a new interface:

![screenshot 30](https://cloud.githubusercontent.com/assets/8996268/18528476/7f3e903a-7ac9-11e6-892d-28f0a3644b1b.png)

The extension cannot select the element to attach the statistics. It was: `#contributions-calendar`.
Now it could be: `.mb-5.border.border-gray-dark.rounded-1.py-3` or `.js-contribution-graph`

Probably we need to tweak some CSS

**Comment by Naramsim** [comment]
Moreover, they added the possibility to navigate through years. So the extension will display statistics only for that period.

**Comment by PuRonglong** [comment]
Nice.Looking forward to the new display.😊

**Comment by Naramsim** [comment]
@PuRonglong Updates are rolling out.
Chrome has received it four hours ago. Does it work?

![screenshot 168](https://cloud.githubusercontent.com/assets/8996268/18548962/d1b7c480-7b4b-11e6-856c-fec4bcdf4eff.png)

I've kept the design simple and removed the divisions between stats.

**Comment by PuRonglong** [comment]
@Naramsim Yes,it works.I give a star to the project for support.
