### ISSUE TITLE
Regression when double clicking a year?

### ISSUE THREAD

**Issue by TDA** [Naramsim/GithubOriginalStreak#49]
Hello, for some reason I believe I double-clicked on the year 2016 on my profile page, resulting in this:
<img width="773" alt="screenshot 2016-10-11 23 44 14" src="https://cloud.githubusercontent.com/assets/432707/19300056/d9e521a4-900c-11e6-9ad2-a3bd8cb4edb6.png">

Thinking this must be a transient issue, I refreshed the page, resulting in this:
<img width="801" alt="screenshot 2016-10-11 23 44 43" src="https://cloud.githubusercontent.com/assets/432707/19300069/f34e6236-900c-11e6-83f8-39b8f4bfa837.png">

But this streak is not right, as my streak starts on Jun 2, 2015:
<img width="765" alt="screenshot 2016-10-11 23 43 44" src="https://cloud.githubusercontent.com/assets/432707/19300081/02171952-900d-11e6-9de3-a6355f5bc684.png">

I seemed to have broken my GithubStreaks plugin, so i uninstalled and re-installed it, and now I am neither able to click on `options` nor set the start date :( Please help me out, as I am almost at 500 now 💃 

@Naramsim

**Comment by Naramsim** [comment]
Hi, I've set your start date back as it were.
There is currently a bug when you click more than once on year buttons.

Now I don't have enough time to investigate, for a couple of weeks you should live with this bug.

However, the extension works correctly now since i restored your initial date

**Comment by TDA** [comment]
@Naramsim Thank you so much! really appreciate it!

**Comment by TDA** [comment]
@Naramsim Seems to have reset to 366 days again, not sure why, didnt even click this time :(

**Comment by Naramsim** [comment]
Updated your data. Don't know why it reset back to 366

**Comment by TDA** [comment]
@Naramsim I seem to have found a way to reproduce this. This seems to happen only when I make a push after 9pm PST. Not sure why :( It has reset back to 371 now. T_T

**Comment by Naramsim** [comment]
Hi @TDA, I think I found a bug that could cause this behavior.
Basically, the start date is deleted with a backup if you do not commit for 2 or more days. But the current regex that reads backups does not work.

`/^(\d{4}-\d{2}-\d{2})?(?:#(\d{4}-\d{2}-\d{2}))?(?:@([01]))?$/` -> correct one 6b69913f436242ed6ee6a5492bbfabf1c33a7ef9

I've updated the regex in order to read backups(only one char added). I am releasing updates in the stores.

**Comment by TDA** [comment]
@Naramsim Thank you so much!! You deserve a pat for fixing stuff so fast!! let me know if you have anything I can do! :)

**Comment by TDA** [comment]
@Naramsim It seems to have reset again. Notice how it says 2 days back even though its still October 20, 10.36PM PST.
<img width="772" alt="screenshot 2016-10-20 22 36 05" src="https://cloud.githubusercontent.com/assets/432707/19587763/b5065604-9715-11e6-8611-31f2e8f68ecd.png">

**Comment by TDA** [comment]
@Naramsim But it has reset back to 507 now after I made todays push!! :D :D so this is indeed fixed!!! can be closed 👍

**Comment by Naramsim** [comment]
Yes, the behavior is this one:
If you don't commit for two days the streak is correctly reset back. A backup is done. If at some moment it appears that you have contributed in those days, the backup is restored.

Good to know that it works!

**Comment by TDA** [comment]
@Naramsim But its not been 2 days :O cuz its still Oct 20th 11.55pm PST

**Comment by Naramsim** [comment]
Hi @TDA, I forgot to write you back.
The stats are drawn by looking at the Github calendar, and in your picture you can see that there are two gray squares, this means that Github think you haven´t contributed for two days.

**Comment by TDA** [comment]
@Naramsim Yes, but after I make a push and refresh, it shows 0 gray squares. That screenshot and the comment were posted on Oct 20th well before midnight PST. But it shows two gray squares for Oct 20 AND Oct 21, which is in the future. Is this a general github thing? Cuz i dont remember having seen that behavior before.

**Comment by Naramsim** [comment]
Yes, it is about Github and how it calculates the time. For me everything is ok (UTC+01:00). I only watch the calendar.
