### ISSUE TITLE
GithubOriginalStreak icon 

### ISSUE THREAD

**Issue by sarbbottam** [Naramsim/GithubOriginalStreak#5]
GithubOriginalStreak icon looks vague compared to others.

<img width="387" alt="screen shot 2016-06-08 at 10 21 31 pm" src="https://cloud.githubusercontent.com/assets/949380/15919559/659f141e-2dc7-11e6-91db-8173fcf7dde0.png">

I have created this one 

![github](https://cloud.githubusercontent.com/assets/949380/15919597/b0a80aa6-2dc7-11e6-9f7c-32b7f2ff0148.png)

With the exact color and aspect ratio of 

<img width="140" alt="screen shot 2016-06-08 at 10 24 12 pm" src="https://cloud.githubusercontent.com/assets/949380/15919605/c69f2e0c-2dc7-11e6-8998-5d2d6fa5d498.png">

Let me know, if you prefer the new one, I can share the SVG file and PNGs in different dimension

**Comment by Gliptal** [comment]
Nice work, better than the original!

**Comment by Naramsim** [comment]
What do you think about this one? @sarbbottam @Gliptal 
![streak_64](https://cloud.githubusercontent.com/assets/8996268/15941107/1069f514-2e7f-11e6-85f2-ffb2d1e5bd42.png)

**Comment by sarbbottam** [comment]
@Naramsim Looks nice, I would reduce the gap, to make it look more compact.

GitHub ratio is 11 : 2, 11 is the width and length of the square and 2 is the gap.

**Comment by sarbbottam** [comment]
### PNG

![github](https://cloud.githubusercontent.com/assets/949380/15943679/083dcaa4-2e3f-11e6-833f-a9ac65d8cf77.png)

### SVG

``` svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="242px" height="242px" viewBox="0 0 242 242" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>GitHub</title>
    <desc>GitHub Commit</desc>
    <g>
        <g>
            <rect id="#D6E685" fill="#D6E685" x="0" y="132" width="110" height="110"></rect>
            <rect id="#8CC665" fill="#1E6823" x="0" y="0" width="110" height="110"></rect>
            <rect id="#44A340" fill="#44A340" x="132" y="0" width="110" height="110"></rect>
            <rect id="#1E6823" fill="#8CC665" x="132" y="132" width="110" height="110"></rect>
        </g>
    </g>
</svg>
```

**Comment by sarbbottam** [comment]
Would you prefer, me to raise a PR with images in different dimension and optimized?

**Comment by Gliptal** [comment]
@sarbbottam 's solution is still the best IMHO, clean and flat looking.

**Comment by Naramsim** [comment]
I will update all the icons on stores tomorrow
