### ISSUE TITLE
Extension Has Stopped Working?

### ISSUE THREAD

**Issue by wbraswell** [Naramsim/GithubOriginalStreak#50]
Some time over the weekend, my extension stopped showing my streak, now it just looks like a normal GitHub page w/out the extension installed.

I have tried disabling and then re-enabling the extension, the GitHub page view does not change at all.

Has something changed with GitHub that has temporarily broken the extension?

Thanks in advance!  :-)

**Comment by Naramsim** [comment]
Hi @wbraswell, thanks for the issue. Github has changed a little bit the padding of the calendar thus invalidating the HTML element that i use to append our statistics.

I chencged the element from `document.querySelectorAll('.mb-5.border.border-gray-dark.rounded-1.py-3')[0];`

to `document.querySelectorAll('.mb-5.border.border-gray-dark.rounded-1.py-2')[0];`

I've released the new version on the various stores, Chrome will receive it in about an hour

**Comment by wbraswell** [comment]
@Naramsim 

Great job!  Mine seems to be working again now, without changing anything.

Was I supposed to actually download and install a new Chrome extension, or did it automatically update itself?

**Comment by Naramsim** [comment]
Chrome and all other browsers (FF & Opera) auto-updates extensions automatically

**Comment by wbraswell** [comment]
:-)

:+1:
