### ISSUE TITLE
Not working in Opera

### ISSUE THREAD

**Issue by futagoza** [Naramsim/GithubOriginalStreak#57]
I just came across this today while looking for a extension to remove the black navbar, but its not working at all, I'm just seeing the normal contributions.

OS: Windows 10 Home x64
Browser: Opera 44.0.2510.1218 (12/04/2017)
Store: [https://addons.opera.com/en-gb/extensions/details/github-original-streak/](https://addons.opera.com/en-gb/extensions/details/github-original-streak/)

**Comment by Naramsim** [comment]
Currently, there is an old version on Opera which does not work, tomorrow I'll release the correct extension in the marketplace. What do you mean by ..?

>  while looking for a extension to remove the black navbar

This extension is not meant to remove the black bar.

Edit: I've submitted it to the store

**Comment by futagoza** [comment]
Sorry, that wasn't meant to be about this extension. I was basically saying that while looking for a [different extension](https://github.com/victor-li/github-white-navbar) I came across [GithubOriginalStreak](https://addons.opera.com/en-gb/extensions/details/github-original-streak/) by accident 😄 

How long does it usually take for an update to appear on the store after you've submitted it?

**Comment by Naramsim** [comment]
Hi, probably two or three days.
When it is published I will close this issue so you will be notified

PS: I suggest [this](https://github.com/DennisSnijder/MakeGithubGreatAgain) extension to bring back the white bar

**Comment by Naramsim** [comment]
@futagoza Opera today approved the extension, can you chack it out?

https://addons.opera.com/en-gb/extensions/details/github-original-streak/

**Comment by futagoza** [comment]
@Naramsim It's working fine now on Opera, thanks.
