### ISSUE TITLE
Calculates longest streak incorrectly.

### ISSUE THREAD

**Issue by ljharb** [Naramsim/GithubOriginalStreak#58]
My current streak is 1113 days (since April 16th, 2014). The extension reports it as 668 days (since July 5th, 2015).

Can this be fixed?

**Comment by Naramsim** [comment]
Hi, yes, I'll update your entry manually. 

Didn't the extension ask you about setting the day about when you started your streak?

**Comment by Naramsim** [comment]
![jordan](https://cloud.githubusercontent.com/assets/8996268/25661138/93f51c00-300f-11e7-8dc1-fa70a2a1608f.PNG)

**Comment by ljharb** [comment]
It's now calculating correctly; it seems that uninstalling and reinstalling the extension didn't fix it, but restarting Chrome seems to have fixed it.

**Comment by ljharb** [comment]
@Naramsim thanks - no, it didn't ask me anything, and I don't see any options.

**Comment by Naramsim** [comment]
Oh, that's a problem, probably with the new design the question is no more appearing, I will investigate. Thanks.
