### ISSUE TITLE
Data should be stored locally

### ISSUE THREAD

**Issue by ifvictr** [Naramsim/GithubOriginalStreak#65]
Hello! I noticed that data was being stored in a remote Gist [here](https://github.com/Naramsim/GithubOriginalStreak/blob/master/src/store.js). Why would local storage not be used in this case?

**Comment by Naramsim** [comment]
To present _all_ the users with the correct full streak. Not only those with a full-calendar.

Maybe we can add a sort of caching in the LS, but we should discuss a little bit about that.
