### ISSUE TITLE
Seems to no longer be working

### ISSUE THREAD

**Issue by ljharb** [Naramsim/GithubOriginalStreak#66]
I'm not sure if Github changed their markup or something, but i see no console errors, and the extension's UI never kicks in (as of a week or three ago)

**Comment by Naramsim** [comment]
Thanks for reporting the issue, probably Github changed the DOM.

I will take a look.

**Comment by Naramsim** [comment]
Hi again, I just pushed a new version to the stores. If you use Chrome you should be able to check if it works again in about 2 hours.

https://github.com/Naramsim/GithubOriginalStreak/commit/4075b93e8a6343444f3a2423b216c181c67d6821

If it works you can close

**Comment by ljharb** [comment]
Works, thanks!!
