### ISSUE TITLE
Duplicates

### ISSUE THREAD

**Issue by endormi** [Naramsim/GithubOriginalStreak#70]
Clicking a year then clicking overview creates a duplicate. Other than that I really enjoy using this! 
![duplicate](https://user-images.githubusercontent.com/39559256/55611902-96981580-578f-11e9-8965-8d89284c70d0.PNG)

**Comment by Naramsim** [comment]
Thanks for reporting, this is the contrary of #68. I don't know if I will have time to check it.

Don't expect a fix any time soon by me.
