### ISSUE TITLE
Longest streak capped at 365 days

### ISSUE THREAD

**Issue by Eurus-Holmes** [Naramsim/GithubOriginalStreak#76]
Why can't my contributions be accumulated, up to 365 days?

On July 26th, 
<img width="966" alt="屏幕快照 2019-07-26 00 11 25" src="https://user-images.githubusercontent.com/34226570/62007703-a365be00-b11e-11e9-8c08-8517fcb10161.png">

On July 28th,
<img width="918" alt="屏幕快照 2019-07-28 09 57 38" src="https://user-images.githubusercontent.com/34226570/62007706-ab256280-b11e-11e9-8dc8-c6b149c1b060.png">

**Comment by Naramsim** [comment]
Looking at [your profile](https://github.com/Eurus-Holmes) with the latest plugin on Chrome it shows you at 381 days. 

![feiyang](https://user-images.githubusercontent.com/8996268/63032004-4e170400-beb5-11e9-85d4-f1865a821ba7.PNG)

Which browser are you on @Eurus-Holmes?

**Comment by Eurus-Holmes** [comment]
Sorry, maybe I misunderstood, I think it should be another [plugin](https://github.com/jasonlong/isometric-contributions) problem...

**Comment by Naramsim** [comment]
Can we close?
