### ISSUE TITLE
Overlay does not fade out

### ISSUE THREAD

**Issue by Eurus-Holmes** [Naramsim/GithubOriginalStreak#77]
The calendar dialog can't be dismissed when I click anywhere else?

**Comment by Naramsim** [comment]
Can you provide a screenshot?

**Comment by Naramsim** [comment]
Investigating

**Comment by Naramsim** [comment]
Deploying an hotfix

**Comment by Naramsim** [comment]
@Eurus-Holmes, I disabled the popup, sorry. In an hour the change should roll-out in Chrome and in a day in Firefox. Can you confirm if the bug will be resolved?

**Comment by Eurus-Holmes** [comment]
@Naramsim Thanks! It has been fixed!

**Comment by Eurus-Holmes** [comment]
@Naramsim This bug occurred again!



<img width="1254" alt="屏幕快照 2019-12-06 下午5 54 53" src="https://user-images.githubusercontent.com/34226570/70313969-87eb8c00-1851-11ea-9340-9934408f53ed.png">

**Comment by webistomin** [comment]
Same problem🤔

**Comment by Naramsim** [comment]
Hello everyone, I'm extremely sorry for this bug happening again. 

I pushed to FF and Chrome webstores a hotfix that simply gets rid of the entire popup.

I hope it won't take much time.

**Comment by Eurus-Holmes** [comment]
@Naramsim It has been fixed! Thanks!
