### ISSUE TITLE
need to add .editorconfig file for format consistency.

### ISSUE THREAD

**Issue by sarbbottam** [Naramsim/GithubOriginalStreak#8]
https://github.com/Naramsim/GithubOriginalStreak/blob/master/src/inject.js is using both `tab` and `space` for indentation. Ideally it should be one, adding an `.editorconfig` file would resolve the issue.

For example https://github.com/sarbbottam/js-ds/blob/master/.editorconfig

**Comment by Naramsim** [comment]
Thanks for pointing it out. I'll add it :+1:
