### ISSUE TITLE
No need for a module badge

### ISSUE THREAD

**Issue by Seluj78** [Naramsim/GithubOriginalStreak#80]
Hey !

It seems that this addon for firefox adds a badge, like shown below

<img width="182" alt="Screenshot 2019-11-15 at 15 04 06" src="https://user-images.githubusercontent.com/4641317/68948881-305d8180-07b9-11ea-92b7-1a8cc78881c8.png">

But it really isn't needed, can it be removed ?

**Comment by Naramsim** [comment]
Could be, I don't know how to do it anyways. Isn't it automatically added by firefox so that you know the extension is installed? Maybe as a security/transparency reason.

**Comment by Seluj78** [comment]
> Could be, I don't know how to do it anyways. Isn't it automatically added by firefox so that you know the extension is installed? Maybe as a security/transparency reason.

I don't think so, it seems that some modules I install don't have one and some do, like yours for example... Maybe in the package settings? I have no clue how it works, I would've looked into it otherwise :)

**Comment by Naramsim** [comment]
Ok, I got it. There is a [`browserAction`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/browserAction) and in my `manifest.json` there is the icon specified. I think removing it solves your problem.

**Comment by Seluj78** [comment]
Are you going to push it ? 😄 or do you want it as is ?

**Comment by Naramsim** [comment]
I'll take a look, I don't a lot of time but I can do it 😄

**Comment by Seluj78** [comment]
Thanks a lot ❤️

**Comment by Naramsim** [comment]
Hi @Seluj78, we have a problem here, I guess. So Chrome forces all extensions to display an icon in the top bar.

Read more here: https://stackoverflow.com/a/37521405/3482533

I removed anyway the `browser_action` and Chrome should thus display the icon grayed-out.

I'm not sure what FF will do. I submitted the new version and in a few days it should update, will you be able to check?

**Comment by Seluj78** [comment]
Hey @Naramsim ! Thanks ! I will check and let you know !

**Comment by Seluj78** [comment]
Hey, it seems to have worked for FF ! Thanks !
