### ISSUE TITLE
visibility

### ISSUE THREAD

**Issue by FatTonyy** [Naramsim/GithubOriginalStreak#82]
visibility is terrible on a dark theme.

[Example](https://res.cloudinary.com/dcbx7o2dn/image/upload/v1597148820/fat-tonyy/Screenshot_1_hlbyrq.png)

**Comment by Naramsim** [comment]
Is that an official Github feature or a browser extension?

**Comment by FatTonyy** [comment]
browser extension.
[link](https://chrome.google.com/webstore/detail/github-dark-theme/odkdlljoangmamjilkamahebpkgpeacp)

**Comment by Naramsim** [comment]
Sorry, then you have to contact that developer. I can't change his CSS, and ~~his source code is not open source~~ (differently to this extension)

Nevermind, it's open source: https://github.com/poychang/github-dark-theme
