### ISSUE TITLE
Firefox release?

### ISSUE THREAD

**Issue by chocolateboy** [Naramsim/GithubOriginalStreak#85]
Any plans for a new Firefox release? The version on [AMO](https://addons.mozilla.org/en-US/firefox/addon/github-original-streak/) (v1.14.9, December 2019) appears to be missing a few updates available in the [Chrome version](https://chrome.google.com/webstore/detail/github-original-streak/jgfeifpakohnblfnjdpigclinhbkocja) (v1.14.10, December 2020).

**Comment by Naramsim** [comment]
Yep, I'll try :)

**Comment by Naramsim** [comment]
@chocolateboy I submitted a new version for FF. Is the extension working as expected?

**Comment by chocolateboy** [comment]
Yes, it works. Thanks!
