### ISSUE TITLE
Anybody else having issues?

### ISSUE THREAD

**Issue by eddelbuettel** [Naramsim/GithubOriginalStreak#86]
Did GitHub change something (again)?  When enabled all I get is this at the top

![image](https://user-images.githubusercontent.com/673121/107078018-53f05b80-67b3-11eb-9b5e-d148944d3d72.png)

and _nothing_ at the bottom:

![image](https://user-images.githubusercontent.com/673121/107078096-75514780-67b3-11eb-914d-64dfba2d1d65.png)

So having the extension 'swallows' their display which shows total count over last year (and nothing else):

![image](https://user-images.githubusercontent.com/673121/107078193-931eac80-67b3-11eb-8eae-89fd422925e5.png)

**Comment by Naramsim** [comment]
Yep, I confirm. Probably they changed the DOM. I'll look into it tomorrow.

**Comment by ian-pvd** [comment]
Looks like an issue here: 
![Screen Shot 2021-02-05 at 21 02 59](https://user-images.githubusercontent.com/1553012/107105755-e87bad80-67f5-11eb-8453-46bf5a684ca9.png)

just glanced under the hood but might need to change `document.getElementsByClassName('day')` => `document.getElementsByClassName('ContributionCalendar-day')` ? Idk, I'm not looking at source.

![Screen Shot 2021-02-05 at 21 07 33](https://user-images.githubusercontent.com/1553012/107105807-309ad000-67f6-11eb-89e2-a079f9611e5a.png)

(thank you)

**Comment by Naramsim** [comment]
@ian-pvd, almost got it :)

It was

```js
document.querySelectorAll('.ContributionCalendar-day[data-count]');
```

**Comment by Naramsim** [comment]
Chrome already made the new version public. I also submitted it to the FF addons marketplace.

**Comment by eddelbuettel** [comment]
I see it in the Chrome app store, my instance is still at the old one. I'll just wait a bit.

Thanks so much as always!

**Comment by ljharb** [comment]
After updating and restarting Chrome, today's extension update seems to be working again. Thank you!

**Comment by eddelbuettel** [comment]
Back up now to working as usual.  Magic.  Yay.  :cake:   Many thanks for looking into it. 

I'll close it as we're thankfully back to normal.
