### ISSUE TITLE
Any way to use a personal token to avoid API rate limit?

### ISSUE THREAD

**Issue by fharper** [Naramsim/GithubOriginalStreak#96]
Any way to use a personal token to avoid API rate limit? When using more than one Chrome extension that doesn't allow to use a personal token, when you spend a lot of time on GH, the rate limit is quickly reached: this would solved the problem if possible.

**Comment by Naramsim** [comment]
Hi Frédéric, good issue. Surely I could implement a way to read the token from a UI input and store it in LS. But I don't have time.. 

Maybe I'll implement only the part of reading the token from LS and pass it to the http calls. But you'll have to add it manually to the LS. 

Anyway, don't expect anything soon, at least from me

**Comment by fharper** [comment]
@Naramsim: sounds good, thanks! If I have time I'll do a PR, but like you, it's a bit too busy right now!

**Comment by Naramsim** [comment]
Hi @fharper, today I looked a bit deeper into this issue. Did you actually get rate-limited?

All the calls to Github's API are done only if necessary (if there is a chance the user has a calendar full of contributions) and they already use a read-only token I generated with a machine user.

**Comment by fharper** [comment]
I do, but maybe it's not from your extension as I'm using 2-3 others which don't have the feature of using their own token: all others have that feature. In the end, it doesn't matter which extensions caused the limitations as once you are limited, yours cannot work :)

**Comment by Naramsim** [comment]
Hmm, ok. Anyways I'm going to close this issue, since the extension is already using a token.

**Comment by fharper** [comment]
> Hmm, ok. Anyways I'm going to close this issue, since the extension is already using a token.

Sounds good, I'll update my version with my token to prevent the issues I have. Thanks a lot for taking the time, I appreciate that :)
